### ISSUE TITLE
StringAttributes are not registering as attributes of the class

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/wc_utils#2]
StringAttributes are not registering as attributes of the class. See the empty set in the error message below. However, the ManyToOne and OneToMany attributes register correctly. What could be the problem?

Sample code
```
class X(core.Model):
	label = core.StringAttribute()

if __name__ == '__main__':
	class Y(X):
		label = 'It is Y now'
	
	a = Y()
	print a.label
```

Error:
```
Traceback (most recent call last):
  File "structures.py", line 43, in <module>
    class Y(X):
  File "c:\wccodebase\wc_utils\wc_utils\schema\core.py", line 209, in __new__
    metacls.validate_attributes(cls)
  File "c:\wccodebase\wc_utils\wc_utils\schema\core.py", line 371, in validate_attributes
    cls.__name__, set(cls.Meta.attributes.keys())))
ValueError: 'label' not found in attributes of Y: set([])
```

**Comment by jonrkarr** [comment]
This syntax is not valid. In the class definition of Y, the attributes should be instances of wc_utils.schema.core.Attribute not specific values.

The following is valid:

```
class X(core.Model):
	label = core.StringAttribute()

if __name__ == '__main__':
	class Y(X):
		pass
	
	a = Y(label='It is Y now')
	print a.label
```
